version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/setup.sh
      timeout: 180
      runas: root